#ifndef SHIET_POLYGON_TEXTURE_H_
#define SHIET_POLYGON_TEXTURE_H_

struct shiet_polygon_texture_s
{
    unsigned width, height;

    /* What kind of filtering to ask the renderer to apply to the texture. The
     * renderer will honor this request if it can; otherwise, it is free to pick
     * a more suitable filtering method.*/
    enum
    {
        SHIET_TEXTURE_FILTER_LINEAR,
        SHIET_TEXTURE_FILTER_NEAREST
    } filtering;

    /* The texture's pixels, as consecutive RGBA values in the range 0-255.*/
    uint8_t *pixelArray;
    
    /* A value that identifies this texture with the specific render API used.
     * For instance, with OpenGL, this might be the value generated by a call
     * to glGenTextures().*/
    int32_t apiId;
};

#endif
