#ifndef SHIET_POLYGON_TEXTURE_H_
#define SHIET_POLYGON_TEXTURE_H_

struct shiet_polygon_texture_s
{
    unsigned width, height;

    /* The texture's pixels, as consecutive r/g/b/a values.*/
    uint8_t *pixelArray;
    
    /* A value that identifies this texture with the specific render API used.
     * For instance, with OpenGL, this might be the value generated by a call
     * to glGenTextures.*/
    int32_t apiId;
};

#endif
